openapi: 3.0.0
info:
  title: Kwik Chat API
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local
  - url: https://kwik-chat-api.fly.dev/
    description: Production
# TODO: Move this to an environment variable with jinja2 templates


tags:
  - name: Chat

paths:
  /chats:
    get:
      tags:
        - Chat
      summary: Get all chats
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    chatId:
                      type: string
                      format: uuid
                    subject:
                      type: string

    post:
      tags:
        - Chat
      summary: Create a new chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                  chatId:
                    type: string
                    format: uuid

  /chats/{chatId}:
    get:
      tags:
        - Chat
      summary: Get a chat by chatId
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The unique identifier of the chat
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      tags:
        - Chat
      summary: Add user message to a chat
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The unique identifier of the chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
